version: 2

sources:
  - name: olist
    database: third-harbor-301722
    schema: Olist
    tables:
      - name: olist_orders_dataset
        description: "Contains all orders."
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: order_status
            tests:
              - not_null

      - name: olist_order_payments_dataset
        description: "Contains payment details."
        columns:
          - name: order_id
            tests:
              - not_null
          - name: payment_value
            tests:
              - not_null

      - name: olist_order_reviews_dataset
        description: "Contains customer reviews."
        columns:
          - name: review_id
            tests:
              - not_null
          - name: review_score
            tests:
              - not_null
              - accepted_values:
                  values: [1, 2, 3, 4, 5]
                  quote: false  


      - name: olist_order_items_dataset
        description: "Contains order items."
        columns:
          - name: order_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null

      - name: olist_products_dataset
        description: "Contains product details."
        columns:
          - name: product_id
            tests:
              - unique
              - not_null

      - name: olist_sellers_dataset
        description: "Contains seller details."
        columns:
          - name: seller_id
            tests:
              - unique
              - not_null

      - name: olist_customers_dataset
        description: "Contains customer details."
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null

      - name: olist_geolocation_dataset
        description: "Contains geolocation data."

      - name: olist_product_category_name_translation
        description: "Contains category translations."